### ISSUE TITLE
Fatal error: this socket is closed

### ISSUE THREAD

**Issue by BenjaminAbt** [robwierzbowski/grunt-build-control#83]
Environment:

- Windows 10 - 14393
- NPM: 3.10.9
- Node: 7.1.0
- grunt cli: 1.2.0

I'm trying to create a git during build and push the results to a git repository. I always getting errors.

**Configuration:**

```
buildcontrol: {
            options: {
                dir: '.build',
                commit: true,
                shallowFetch: false,
                force: true,
                push: true,
                message: 'Built %sourceName% from commit %sourceCommit% on branch %sourceBranch%',
                connectCommits: false
            },
            vsts: {
                options: {
                    remote: 'https://xxxx.visualstudio.com/DefaultCollection/xxxx/_git/xxxx',
                    login: 'xxxx',
                    token: 'xxxx',
                    branch: 'master',
                }
            },
            azure: {
                options: {
                    remote: 'https://xxxx.scm.azurewebsites.net:443/xxxx.git',
                    login: 'xxxx',
                    token: 'xxxx',
                    branch: 'master',
                }
            }
        }
```

**Azure:**

```
Running "buildcontrol:azure" (buildcontrol) task
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: This socket is closed
  at WriteStream.Socket._writeGeneric (net.js:683:19)
  at WriteStream.Socket._write (net.js:734:8)
  at doWrite (_stream_writable.js:334:12)
  at writeOrBuffer (_stream_writable.js:320:5)
  at WriteStream.Writable.write (_stream_writable.js:247:11)
  at WriteStream.Socket.write (net.js:661:40)
  at Log._write (G:\_data\r\xxxx\src\node_modules\grunt-legacy-log\index.js:161:26)
  at Log.wrapper [as _write] (G:\_data\r\xxxx\src\node_modules\lodash\index.js:3095:19)
  at Log._writeln (G:\_data\r\xxxx\src\node_modules\grunt-legacy-log\index.js:166:8)
  at Log.wrapper [as _writeln] (G:\_data\r\xxxx\src\node_modules\lodash\index.js:3095:19)
  at Log.writeln (G:\_data\r\xxxx\src\node_modules\grunt-legacy-log\index.js:177:8)
  at Log.wrapper (G:\_data\r\xxxx\src\node_modules\lodash\index.js:3095:19)
  at writeln (G:\_data\r\xxxx\src\node_modules\grunt\lib\grunt\fail.js:30:13)
  at Object.fail.fatal (G:\_data\r\xxxx\src\node_modules\grunt\lib\grunt\fail.js:46:3)
  at process.uncaughtHandler (G:\_data\r\xxxx\src\node_modules\grunt\lib\grunt.js:121:10)
  at emitOne (events.js:96:13)
  at process.emit (events.js:188:7)
  at process._fatalException (bootstrap_node.js:292:26)
```

**Visual Studio Team Services:**

```
Running "buildcontrol:vsts" (buildcontrol) task

Fetching "master" files from https://xxxx.visualstudio.com/DefaultCollection/xxxx/_git/xxxx.
POST git-upload-pack (117 bytes)
POST git-upload-pack (126 bytes)
remote:
remote:                    vSTs
remote:                  vSTSVSTSv
remote:                vSTSVSTSVST
remote: VSTS         vSTSVSTSVSTSV
remote: VSTSVS     vSTSVSTSV STSVS
remote: VSTSVSTSvsTSVSTSVS   TSVST
remote: VS  tSVSTSVSTSv      STSVS
remote: VS   tSVSTSVST       SVSTS
remote: VS tSVSTSVSTSVSts    VSTSV
remote: VSTSVST    SVSTSVSTs VSTSV
remote: VSTSv        STSVSTSVSTSVS
remote:                VSTSVSTSVST
remote:                  VSTSVSTs
remote:                    VSTs    (TM)
remote:
remote:  Microsoft (R) Visual Studio (R) Team Services
remote:
remote: Found 3 objects to send. (26 ms)
From https://xxxx.visualstudio.com/DefaultCollection/xxxx/_git/xxxx-LIVE
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> remote-f70d2a/master
Branch master set up to track remote branch master from remote-f70d2a.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: This socket is closed
  at WriteStream.Socket._writeGeneric (net.js:683:19)
  at WriteStream.Socket._write (net.js:734:8)
  at doWrite (_stream_writable.js:334:12)
  at writeOrBuffer (_stream_writable.js:320:5)
  at WriteStream.Writable.write (_stream_writable.js:247:11)
  at WriteStream.Socket.write (net.js:661:40)
  at Log._write (G:\_data\r\xxxx\src\node_modules\grunt-legacy-log\index.js:161:26)
  at Log.wrapper [as _write] (G:\_data\r\xxxx\src\node_modules\lodash\index.js:3095:19)
  at Log._writeln (G:\_data\r\xxxx\src\node_modules\grunt-legacy-log\index.js:166:8)
  at Log.wrapper [as _writeln] (G:\_data\r\xxxx\src\node_modules\lodash\index.js:3095:19)
  at Log.writeln (G:\_data\r\xxxx\src\node_modules\grunt-legacy-log\index.js:177:8)
  at Log.wrapper (G:\_data\r\xxxx\src\node_modules\lodash\index.js:3095:19)
  at writeln (G:\_data\r\xxxx\src\node_modules\grunt\lib\grunt\fail.js:30:13)
  at Object.fail.fatal (G:\_data\r\xxxx\src\node_modules\grunt\lib\grunt\fail.js:46:3)
  at process.uncaughtHandler (G:\_data\r\xxxx\src\node_modules\grunt\lib\grunt.js:121:10)
  at emitOne (events.js:96:13)
  at process.emit (events.js:188:7)
  at process._fatalException (bootstrap_node.js:292:26)
```

When I work with SourceTree, all credentials work fine. Thanks for help.

**Comment by kevinawoo** [comment]
Is buildcontrol part of another grunt task, if so, can you buildcontrol by itself?

**Comment by BenjaminAbt** [comment]
Both. It is part of a multiple task configuration and also a single task.
Same result.

**Comment by BenjaminAbt** [comment]
If i use inline credentials `https://username:password@xxxx.scm.azurewebsites.net:443/xxxx.git` i get this:

```
Running "buildcontrol:azure" (buildcontrol) task

Fetching "dist" history from https://xxxx:xxxx@xxxx.scm.azurewebsites.net:443/xxxx.git.
POST git-upload-pack (151 bytes)
remote: Total 3466 (delta 700), reused 3233 (delta 561)
Resolving deltas: 100% (700/700), done.
From https://xxxx.scm.azurewebsites.net:443/xxxx
 * branch            dist       -> FETCH_HEAD
 * [new branch]      dist       -> remote-994815/dist
Branch dist set up to track remote branch dist from remote-994815.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: This socket is closed
  at WriteStream.Socket._writeGeneric (net.js:683:19)
  at WriteStream.Socket._write (net.js:734:8)
  at doWrite (_stream_writable.js:334:12)
  at writeOrBuffer (_stream_writable.js:320:5)
  at WriteStream.Writable.write (_stream_writable.js:247:11)
  at WriteStream.Socket.write (net.js:661:40)
  at Log._write (G:\_data\r\xxxx\src\node_modules\grunt-legacy-log\index.js:161:26)
  at Log.wrapper [as _write] (G:\_data\r\xxxx\src\node_modules\lodash\index.js:3095:19)
  at Log._writeln (G:\_data\r\xxxx\src\node_modules\grunt-legacy-log\index.js:166:8)
  at Log.wrapper [as _writeln] (G:\_data\r\xxxx\src\node_modules\lodash\index.js:3095:19)
  at Log.writeln (G:\_data\r\xxxx\src\node_modules\grunt-legacy-log\index.js:177:8)
  at Log.wrapper (G:\_data\r\xxxx\src\node_modules\lodash\index.js:3095:19)
  at writeln (G:\_data\r\xxxx\src\node_modules\grunt\lib\grunt\fail.js:30:13)
  at Object.fail.fatal (G:\_data\r\xxxx\src\node_modules\grunt\lib\grunt\fail.js:46:3)
  at process.uncaughtHandler (G:\_data\r\xxxx\src\node_modules\grunt\lib\grunt.js:121:10)
  at emitOne (events.js:96:13)
  at process.emit (events.js:188:7)
  at process._fatalException (bootstrap_node.js:292:26)
```

**Comment by BenjaminAbt** [comment]
If I activate `shallowFetch: true` I get this:

```
Running "buildcontrol:azure" (buildcontrol) task

Fetching "dist" files from https://xxxx:xxxx@xxxx.scm.azurewebsites.net:443/xxxx.git.
POST git-upload-pack (154 bytes)
fatal: protocol error: bad line length character: <!DO
POST git-upload-pack (813 bytes)
Warning: POST git-upload-pack (154 bytes)
fatal: protocol error: bad line length character: <!DO
POST git-upload-pack (813 bytes)
 Use --force to continue.

Aborted due to warnings.

```

**Comment by BenjaminAbt** [comment]
If i set `remoteBranch: 'master'` I get this:

```
Running "buildcontrol:azure" (buildcontrol) task

Creating git repository in ".build".
Initialized empty Git repository in G:/_data/r/xxxx/src/.build/.git/

Creating remote.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: This socket is closed
  at WriteStream.Socket._writeGeneric (net.js:683:19)
  at WriteStream.Socket._write (net.js:734:8)
  at doWrite (_stream_writable.js:334:12)
  at writeOrBuffer (_stream_writable.js:320:5)
  at WriteStream.Writable.write (_stream_writable.js:247:11)
  at WriteStream.Socket.write (net.js:661:40)
  at Log._write (G:\_data\r\xxxx\src\node_modules\grunt-legacy-log\index.js:161:26)
  at Log.wrapper [as _write] (G:\_data\r\xxxx\src\node_modules\lodash\index.js:3095:19)
  at Log._writeln (G:\_data\r\xxxx\src\node_modules\grunt-legacy-log\index.js:166:8)
  at Log.wrapper [as _writeln] (G:\_data\r\xxxx\src\node_modules\lodash\index.js:3095:19)
  at Log.writeln (G:\_data\r\xxxx\src\node_modules\grunt-legacy-log\index.js:177:8)
  at Log.wrapper (G:\_data\r\xxxx\src\node_modules\lodash\index.js:3095:19)
  at writeln (G:\_data\r\xxxx\src\node_modules\grunt\lib\grunt\fail.js:30:13)
  at Object.fail.fatal (G:\_data\r\xxxx\src\node_modules\grunt\lib\grunt\fail.js:46:3)
  at process.uncaughtHandler (G:\_data\r\xxxx\src\node_modules\grunt\lib\grunt.js:121:10)
  at emitOne (events.js:96:13)
  at process.emit (events.js:188:7)
  at process._fatalException (bootstrap_node.js:292:26)
```

Now I am end of ideas.

**Comment by BenjaminAbt** [comment]
Maybe it's a general npm issue. https://github.com/nodejs/node/issues/9542

**Comment by BenjaminAbt** [comment]
I switched back to node v6.9.1 and it works.
