### ISSUE TITLE
POST /login 302 653.342 ms - 28 Error: Failed to lookup view "accounts/login" in views directory "C:\Users\Hp\ecommerce\views"

### ISSUE THREAD

**Issue by Awais512** [robwierzbowski/grunt-build-control#85]
I got this error when i try to  send data via postman 

POST /login 302 653.342 ms - 28
Error: Failed to lookup view "accounts/login" in views directory "C:\Users\Hp\ecommerce\views"
    at Function.render (C:\Users\Hp\ecommerce\node_modules\express\lib\application.js:580:17)
    at ServerResponse.render (C:\Users\Hp\ecommerce\node_modules\express\lib\response.js:1008:7)
    at ServerResponse.res.render (C:\Users\Hp\ecommerce\node_modules\express-flash\lib\express-flash.js:29:16)
    at C:\Users\Hp\ecommerce\routes\user.js:8:5
    at Layer.handle [as handle_request] (C:\Users\Hp\ecommerce\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Hp\ecommerce\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\Hp\ecommerce\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\Hp\ecommerce\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Hp\ecommerce\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\Hp\ecommerce\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\Hp\ecommerce\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\Hp\ecommerce\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\Hp\ecommerce\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\Hp\ecommerce\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\Hp\ecommerce\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\Hp\ecommerce\node_modules\express\lib\router\index.js:284:7
GET /login 500 1999.541 ms - 1916

Help me to resolve this issue plzzzzz any help would be appreciated

**Comment by kevinawoo** [comment]
If you're using the grunt-build-control to package it up, it sounds like the view's folder never made it in there. Take a look at your tasks before running `grunt-build-control`, probably a copy task.

**Comment by Awais512** [comment]
M not using grunt-build-control
